//! zsys-bindings — safe Rust wrappers over the zsys C shared library.
//!
//! Raw FFI declarations are auto-generated by build.rs + bindgen from
//! zsys_core.h. This module exposes safe, idiomatic Rust types.

#![allow(non_upper_case_globals, non_camel_case_types, dead_code)]

use std::ffi::{CStr, CString};

mod ffi {
    #![allow(non_upper_case_globals, non_camel_case_types, dead_code)]
    include!(concat!(env!("OUT_DIR"), "/zsys_bindings.rs"));
}

// ── Router ────────────────────────────────────────────────────────────────

/// Safe wrapper over `ZsysRouter` (open-addressing hash table).
pub struct Router(*mut ffi::ZsysRouter);

impl Router {
    /// Allocate a new router, or return `None` on allocation failure.
    pub fn new() -> Option<Self> {
        let ptr = unsafe { ffi::zsys_router_new() };
        if ptr.is_null() { None } else { Some(Router(ptr)) }
    }

    /// Add or update `trigger → handler_id`. Returns 0 on success.
    pub fn add(&mut self, trigger: &str, handler_id: i32) -> i32 {
        let ct = CString::new(trigger).unwrap_or_default();
        unsafe { ffi::zsys_router_add(self.0, ct.as_ptr(), handler_id) }
    }

    /// Remove a trigger. Returns 0 on success, -1 if not found.
    pub fn remove(&mut self, trigger: &str) -> i32 {
        let ct = CString::new(trigger).unwrap_or_default();
        unsafe { ffi::zsys_router_remove(self.0, ct.as_ptr()) }
    }

    /// Return handler_id for trigger, or -1 (case-insensitive lookup).
    pub fn lookup(&self, trigger: &str) -> i32 {
        let ct = CString::new(trigger).unwrap_or_default();
        unsafe { ffi::zsys_router_lookup(self.0, ct.as_ptr()) }
    }

    /// Return the number of registered triggers.
    pub fn count(&self) -> usize {
        unsafe { ffi::zsys_router_count(self.0) }
    }

    /// Remove all triggers.
    pub fn clear(&mut self) {
        unsafe { ffi::zsys_router_clear(self.0) }
    }
}

impl Drop for Router {
    fn drop(&mut self) {
        if !self.0.is_null() {
            unsafe { ffi::zsys_router_free(self.0) };
        }
    }
}

// ── Registry ──────────────────────────────────────────────────────────────

/// Safe wrapper over `ZsysRegistry` (dynamic array: name → handler_id + metadata).
pub struct Registry(*mut ffi::ZsysRegistry);

impl Registry {
    /// Allocate a new registry, or return `None` on allocation failure.
    pub fn new() -> Option<Self> {
        let ptr = unsafe { ffi::zsys_registry_new() };
        if ptr.is_null() { None } else { Some(Registry(ptr)) }
    }

    /// Register `name → handler_id` with optional description and category.
    pub fn register(
        &mut self,
        name: &str,
        handler_id: i32,
        desc: &str,
        cat: &str,
    ) -> i32 {
        let cn = CString::new(name).unwrap_or_default();
        let cd = CString::new(desc).unwrap_or_default();
        let cc = CString::new(cat).unwrap_or_default();
        unsafe {
            ffi::zsys_registry_register(
                self.0,
                cn.as_ptr(),
                handler_id,
                cd.as_ptr(),
                cc.as_ptr(),
            )
        }
    }

    /// Unregister by name. Returns 0 on success, -1 if not found.
    pub fn unregister(&mut self, name: &str) -> i32 {
        let cn = CString::new(name).unwrap_or_default();
        unsafe { ffi::zsys_registry_unregister(self.0, cn.as_ptr()) }
    }

    /// Return handler_id for name, or -1 if not found.
    pub fn get(&self, name: &str) -> i32 {
        let cn = CString::new(name).unwrap_or_default();
        unsafe { ffi::zsys_registry_get(self.0, cn.as_ptr()) }
    }

    /// Return number of registered entries.
    pub fn count(&self) -> usize {
        unsafe { ffi::zsys_registry_count(self.0) }
    }

    /// Return the name at index `i`, or `None` if out of range.
    pub fn name_at(&self, i: usize) -> Option<String> {
        let ptr = unsafe { ffi::zsys_registry_name_at(self.0, i) };
        if ptr.is_null() { return None; }
        Some(unsafe { CStr::from_ptr(ptr) }.to_string_lossy().into_owned())
    }
}

impl Drop for Registry {
    fn drop(&mut self) {
        if !self.0.is_null() {
            unsafe { ffi::zsys_registry_free(self.0) };
        }
    }
}

// ── I18n ──────────────────────────────────────────────────────────────────

/// Safe wrapper over `ZsysI18n` (flat JSON loader, per-language key→value tables).
pub struct I18n(*mut ffi::ZsysI18n);

impl I18n {
    /// Allocate a new I18n context, or return `None` on allocation failure.
    pub fn new() -> Option<Self> {
        let ptr = unsafe { ffi::zsys_i18n_new() };
        if ptr.is_null() { None } else { Some(I18n(ptr)) }
    }

    /// Load a flat `{"key":"value"}` JSON file for `lang_code`.
    pub fn load_json(&mut self, lang_code: &str, json_path: &str) -> i32 {
        let cl = CString::new(lang_code).unwrap_or_default();
        let cp = CString::new(json_path).unwrap_or_default();
        unsafe { ffi::zsys_i18n_load_json(self.0, cl.as_ptr(), cp.as_ptr()) }
    }

    /// Set the active language used by `get()`.
    pub fn set_lang(&mut self, lang_code: &str) {
        let cl = CString::new(lang_code).unwrap_or_default();
        unsafe { ffi::zsys_i18n_set_lang(self.0, cl.as_ptr()) }
    }

    /// Translate `key` using the active language; returns `key` if not found.
    pub fn get(&self, key: &str) -> String {
        let ck = CString::new(key).unwrap_or_default();
        let r = unsafe { ffi::zsys_i18n_get(self.0, ck.as_ptr()) };
        if r.is_null() { return key.to_owned(); }
        unsafe { CStr::from_ptr(r) }.to_string_lossy().into_owned()
    }

    /// Translate `key` in a specific language; returns `key` if not found.
    pub fn get_lang(&self, lang_code: &str, key: &str) -> String {
        let cl = CString::new(lang_code).unwrap_or_default();
        let ck = CString::new(key).unwrap_or_default();
        let r = unsafe { ffi::zsys_i18n_get_lang(self.0, cl.as_ptr(), ck.as_ptr()) };
        if r.is_null() { return key.to_owned(); }
        unsafe { CStr::from_ptr(r) }.to_string_lossy().into_owned()
    }
}

impl Drop for I18n {
    fn drop(&mut self) {
        if !self.0.is_null() {
            unsafe { ffi::zsys_i18n_free(self.0) };
        }
    }
}
