//! Safe Rust wrappers for `libzsys_core` — ZsysUser, ZsysChat, ZsysClientConfig.
//!
//! The raw FFI layer is generated by bindgen at build time and lives in the
//! private `sys` module.  All public types are safe, own their C heap allocation
//! via `Drop`, and implement `Send`.

#![allow(non_upper_case_globals, non_camel_case_types, non_snake_case)]

mod sys {
    include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
}

use std::ffi::{CStr, CString};
use std::os::raw::c_char;

// ─── helpers ─────────────────────────────────────────────────────────────────

/// Convert a raw nullable C string to an owned `Option<String>`.
unsafe fn cstr_to_option(ptr: *const c_char) -> Option<String> {
    if ptr.is_null() {
        None
    } else {
        Some(CStr::from_ptr(ptr).to_string_lossy().into_owned())
    }
}

/// Encode an `Option<&str>` to a `CString`; `None` → null pointer.
fn option_to_cstring(s: Option<&str>) -> (*const c_char, Option<CString>) {
    match s {
        Some(v) => {
            let cs = CString::new(v).expect("string contains null byte");
            let ptr = cs.as_ptr();
            (ptr, Some(cs))
        }
        None => (std::ptr::null(), None),
    }
}

// ═══════════════════════════════ User ════════════════════════════════════════

/// Safe wrapper around `ZsysUser`.
pub struct User {
    ptr: *mut sys::ZsysUser,
}

unsafe impl Send for User {}

impl User {
    /// Allocate a new zero-initialised user.
    pub fn new() -> Result<Self, &'static str> {
        let ptr = unsafe { sys::zsys_user_new() };
        if ptr.is_null() {
            Err("zsys_user_new() returned NULL")
        } else {
            Ok(Self { ptr })
        }
    }

    // ── accessors ─────────────────────────────────────────────────────────

    pub fn id(&self) -> i64 {
        unsafe { (*self.ptr).id }
    }

    pub fn set_id(&mut self, v: i64) {
        unsafe { (*self.ptr).id = v }
    }

    pub fn username(&self) -> Option<String> {
        unsafe { cstr_to_option((*self.ptr).username) }
    }

    pub fn set_username(&mut self, v: Option<&str>) {
        let (ptr, _keep) = option_to_cstring(v);
        unsafe { sys::zsys_user_set_username(self.ptr, ptr) };
    }

    pub fn first_name(&self) -> Option<String> {
        unsafe { cstr_to_option((*self.ptr).first_name) }
    }

    pub fn set_first_name(&mut self, v: &str) {
        let cs = CString::new(v).unwrap();
        unsafe { sys::zsys_user_set_first_name(self.ptr, cs.as_ptr()) };
    }

    pub fn last_name(&self) -> Option<String> {
        unsafe { cstr_to_option((*self.ptr).last_name) }
    }

    pub fn set_last_name(&mut self, v: Option<&str>) {
        let (ptr, _keep) = option_to_cstring(v);
        unsafe { sys::zsys_user_set_last_name(self.ptr, ptr) };
    }

    pub fn phone(&self) -> Option<String> {
        unsafe { cstr_to_option((*self.ptr).phone) }
    }

    pub fn set_phone(&mut self, v: Option<&str>) {
        let (ptr, _keep) = option_to_cstring(v);
        unsafe { sys::zsys_user_set_phone(self.ptr, ptr) };
    }

    pub fn lang_code(&self) -> Option<String> {
        unsafe { cstr_to_option((*self.ptr).lang_code) }
    }

    pub fn set_lang_code(&mut self, v: Option<&str>) {
        let (ptr, _keep) = option_to_cstring(v);
        unsafe { sys::zsys_user_set_lang_code(self.ptr, ptr) };
    }

    pub fn is_bot(&self) -> bool {
        unsafe { (*self.ptr).is_bot != 0 }
    }

    pub fn set_is_bot(&mut self, v: bool) {
        unsafe { (*self.ptr).is_bot = v as i32 }
    }

    pub fn is_premium(&self) -> bool {
        unsafe { (*self.ptr).is_premium != 0 }
    }

    pub fn set_is_premium(&mut self, v: bool) {
        unsafe { (*self.ptr).is_premium = v as i32 }
    }

    pub fn created_at(&self) -> i64 {
        unsafe { (*self.ptr).created_at }
    }

    pub fn set_created_at(&mut self, v: i64) {
        unsafe { (*self.ptr).created_at = v }
    }

    // ── serialisation ─────────────────────────────────────────────────────

    pub fn to_json(&self) -> Result<String, &'static str> {
        let raw = unsafe { sys::zsys_user_to_json(self.ptr) };
        if raw.is_null() {
            return Err("zsys_user_to_json() failed");
        }
        let s = unsafe { CStr::from_ptr(raw).to_string_lossy().into_owned() };
        unsafe { sys::zsys_free(raw as *mut _) };
        Ok(s)
    }

    pub fn from_json(json: &str) -> Result<Self, &'static str> {
        let mut obj = Self::new()?;
        let cs = CString::new(json).map_err(|_| "null byte in json")?;
        let rc = unsafe { sys::zsys_user_from_json(obj.ptr, cs.as_ptr()) };
        if rc != 0 {
            Err("zsys_user_from_json() parse error")
        } else {
            Ok(obj)
        }
    }
}

impl Drop for User {
    fn drop(&mut self) {
        unsafe { sys::zsys_user_free(self.ptr) }
    }
}

impl std::fmt::Debug for User {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("User")
            .field("id", &self.id())
            .field("username", &self.username())
            .field("first_name", &self.first_name())
            .finish()
    }
}

// ═══════════════════════════════ ChatType ════════════════════════════════════

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ChatType {
    Private    = 0,
    Group      = 1,
    Supergroup = 2,
    Channel    = 3,
    Bot        = 4,
}

impl From<sys::ZsysChatType> for ChatType {
    fn from(v: sys::ZsysChatType) -> Self {
        match v {
            sys::ZsysChatType::ZSYS_CHAT_PRIVATE    => ChatType::Private,
            sys::ZsysChatType::ZSYS_CHAT_GROUP      => ChatType::Group,
            sys::ZsysChatType::ZSYS_CHAT_SUPERGROUP => ChatType::Supergroup,
            sys::ZsysChatType::ZSYS_CHAT_CHANNEL    => ChatType::Channel,
            sys::ZsysChatType::ZSYS_CHAT_BOT        => ChatType::Bot,
        }
    }
}

impl From<ChatType> for sys::ZsysChatType {
    fn from(v: ChatType) -> Self {
        match v {
            ChatType::Private    => sys::ZsysChatType::ZSYS_CHAT_PRIVATE,
            ChatType::Group      => sys::ZsysChatType::ZSYS_CHAT_GROUP,
            ChatType::Supergroup => sys::ZsysChatType::ZSYS_CHAT_SUPERGROUP,
            ChatType::Channel    => sys::ZsysChatType::ZSYS_CHAT_CHANNEL,
            ChatType::Bot        => sys::ZsysChatType::ZSYS_CHAT_BOT,
        }
    }
}

// ═══════════════════════════════ Chat ════════════════════════════════════════

/// Safe wrapper around `ZsysChat`.
pub struct Chat {
    ptr: *mut sys::ZsysChat,
}

unsafe impl Send for Chat {}

impl Chat {
    pub fn new() -> Result<Self, &'static str> {
        let ptr = unsafe { sys::zsys_chat_new() };
        if ptr.is_null() {
            Err("zsys_chat_new() returned NULL")
        } else {
            Ok(Self { ptr })
        }
    }

    // ── accessors ─────────────────────────────────────────────────────────

    pub fn id(&self) -> i64 {
        unsafe { (*self.ptr).id }
    }

    pub fn set_id(&mut self, v: i64) {
        unsafe { (*self.ptr).id = v }
    }

    pub fn chat_type(&self) -> ChatType {
        unsafe { ChatType::from((*self.ptr).type_) }
    }

    pub fn set_chat_type(&mut self, v: ChatType) {
        unsafe { (*self.ptr).type_ = sys::ZsysChatType::from(v) }
    }

    pub fn title(&self) -> Option<String> {
        unsafe { cstr_to_option((*self.ptr).title) }
    }

    pub fn set_title(&mut self, v: Option<&str>) {
        let (ptr, _keep) = option_to_cstring(v);
        unsafe { sys::zsys_chat_set_title(self.ptr, ptr) };
    }

    pub fn username(&self) -> Option<String> {
        unsafe { cstr_to_option((*self.ptr).username) }
    }

    pub fn set_username(&mut self, v: Option<&str>) {
        let (ptr, _keep) = option_to_cstring(v);
        unsafe { sys::zsys_chat_set_username(self.ptr, ptr) };
    }

    pub fn description(&self) -> Option<String> {
        unsafe { cstr_to_option((*self.ptr).description) }
    }

    pub fn set_description(&mut self, v: Option<&str>) {
        let (ptr, _keep) = option_to_cstring(v);
        unsafe { sys::zsys_chat_set_description(self.ptr, ptr) };
    }

    pub fn member_count(&self) -> i32 {
        unsafe { (*self.ptr).member_count }
    }

    pub fn set_member_count(&mut self, v: i32) {
        unsafe { (*self.ptr).member_count = v }
    }

    pub fn is_restricted(&self) -> bool {
        unsafe { (*self.ptr).is_restricted != 0 }
    }

    pub fn is_scam(&self) -> bool {
        unsafe { (*self.ptr).is_scam != 0 }
    }

    pub fn created_at(&self) -> i64 {
        unsafe { (*self.ptr).created_at }
    }

    // ── serialisation ─────────────────────────────────────────────────────

    pub fn to_json(&self) -> Result<String, &'static str> {
        let raw = unsafe { sys::zsys_chat_to_json(self.ptr) };
        if raw.is_null() {
            return Err("zsys_chat_to_json() failed");
        }
        let s = unsafe { CStr::from_ptr(raw).to_string_lossy().into_owned() };
        unsafe { sys::zsys_free(raw as *mut _) };
        Ok(s)
    }

    pub fn from_json(json: &str) -> Result<Self, &'static str> {
        let mut obj = Self::new()?;
        let cs = CString::new(json).map_err(|_| "null byte in json")?;
        let rc = unsafe { sys::zsys_chat_from_json(obj.ptr, cs.as_ptr()) };
        if rc != 0 {
            Err("zsys_chat_from_json() parse error")
        } else {
            Ok(obj)
        }
    }
}

impl Drop for Chat {
    fn drop(&mut self) {
        unsafe { sys::zsys_chat_free(self.ptr) }
    }
}

impl std::fmt::Debug for Chat {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("Chat")
            .field("id", &self.id())
            .field("type", &self.chat_type())
            .field("title", &self.title())
            .finish()
    }
}

// ═══════════════════════════════ ClientMode ══════════════════════════════════

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ClientMode {
    User = 0,
    Bot  = 1,
}

impl From<sys::ZsysClientMode> for ClientMode {
    fn from(v: sys::ZsysClientMode) -> Self {
        match v {
            sys::ZsysClientMode::ZSYS_CLIENT_USER => ClientMode::User,
            sys::ZsysClientMode::ZSYS_CLIENT_BOT  => ClientMode::Bot,
        }
    }
}

impl From<ClientMode> for sys::ZsysClientMode {
    fn from(v: ClientMode) -> Self {
        match v {
            ClientMode::User => sys::ZsysClientMode::ZSYS_CLIENT_USER,
            ClientMode::Bot  => sys::ZsysClientMode::ZSYS_CLIENT_BOT,
        }
    }
}

// ═══════════════════════════════ ClientConfig ═════════════════════════════════

/// Safe wrapper around `ZsysClientConfig`.
pub struct ClientConfig {
    ptr: *mut sys::ZsysClientConfig,
}

unsafe impl Send for ClientConfig {}

impl ClientConfig {
    pub fn new() -> Result<Self, &'static str> {
        let ptr = unsafe { sys::zsys_client_config_new() };
        if ptr.is_null() {
            Err("zsys_client_config_new() returned NULL")
        } else {
            Ok(Self { ptr })
        }
    }

    // ── accessors ─────────────────────────────────────────────────────────

    pub fn api_id(&self) -> i32 {
        unsafe { (*self.ptr).api_id }
    }

    pub fn set_api_id(&mut self, v: i32) {
        unsafe { (*self.ptr).api_id = v }
    }

    pub fn api_hash(&self) -> Option<String> {
        unsafe { cstr_to_option((*self.ptr).api_hash) }
    }

    pub fn set_api_hash(&mut self, v: &str) {
        let cs = CString::new(v).unwrap();
        unsafe { sys::zsys_client_set_api_hash(self.ptr, cs.as_ptr()) };
    }

    pub fn session_name(&self) -> Option<String> {
        unsafe { cstr_to_option((*self.ptr).session_name) }
    }

    pub fn set_session_name(&mut self, v: &str) {
        let cs = CString::new(v).unwrap();
        unsafe { sys::zsys_client_set_session_name(self.ptr, cs.as_ptr()) };
    }

    pub fn mode(&self) -> ClientMode {
        unsafe { ClientMode::from((*self.ptr).mode) }
    }

    pub fn set_mode(&mut self, v: ClientMode) {
        unsafe { (*self.ptr).mode = sys::ZsysClientMode::from(v) }
    }

    pub fn phone(&self) -> Option<String> {
        unsafe { cstr_to_option((*self.ptr).phone) }
    }

    pub fn set_phone(&mut self, v: Option<&str>) {
        let (ptr, _keep) = option_to_cstring(v);
        unsafe { sys::zsys_client_set_phone(self.ptr, ptr) };
    }

    pub fn bot_token(&self) -> Option<String> {
        unsafe { cstr_to_option((*self.ptr).bot_token) }
    }

    pub fn set_bot_token(&mut self, v: Option<&str>) {
        let (ptr, _keep) = option_to_cstring(v);
        unsafe { sys::zsys_client_set_bot_token(self.ptr, ptr) };
    }

    pub fn device_model(&self) -> Option<String> {
        unsafe { cstr_to_option((*self.ptr).device_model) }
    }

    pub fn set_device_model(&mut self, v: Option<&str>) {
        let (ptr, _keep) = option_to_cstring(v);
        unsafe { sys::zsys_client_set_device_model(self.ptr, ptr) };
    }

    pub fn system_version(&self) -> Option<String> {
        unsafe { cstr_to_option((*self.ptr).system_version) }
    }

    pub fn set_system_version(&mut self, v: Option<&str>) {
        let (ptr, _keep) = option_to_cstring(v);
        unsafe { sys::zsys_client_set_system_version(self.ptr, ptr) };
    }

    pub fn app_version(&self) -> Option<String> {
        unsafe { cstr_to_option((*self.ptr).app_version) }
    }

    pub fn set_app_version(&mut self, v: Option<&str>) {
        let (ptr, _keep) = option_to_cstring(v);
        unsafe { sys::zsys_client_set_app_version(self.ptr, ptr) };
    }

    pub fn lang_code(&self) -> Option<String> {
        unsafe { cstr_to_option((*self.ptr).lang_code) }
    }

    pub fn set_lang_code(&mut self, v: Option<&str>) {
        let (ptr, _keep) = option_to_cstring(v);
        unsafe { sys::zsys_client_set_lang_code(self.ptr, ptr) };
    }

    pub fn lang_pack(&self) -> Option<String> {
        unsafe { cstr_to_option((*self.ptr).lang_pack) }
    }

    pub fn set_lang_pack(&mut self, v: Option<&str>) {
        let (ptr, _keep) = option_to_cstring(v);
        unsafe { sys::zsys_client_set_lang_pack(self.ptr, ptr) };
    }

    pub fn proxy_host(&self) -> Option<String> {
        unsafe { cstr_to_option((*self.ptr).proxy_host) }
    }

    pub fn proxy_port(&self) -> i32 {
        unsafe { (*self.ptr).proxy_port }
    }

    pub fn proxy_user(&self) -> Option<String> {
        unsafe { cstr_to_option((*self.ptr).proxy_user) }
    }

    pub fn set_proxy(
        &mut self,
        host: &str,
        port: i32,
        user: Option<&str>,
        pass: Option<&str>,
    ) {
        let host_cs = CString::new(host).unwrap();
        let (user_ptr, _u) = option_to_cstring(user);
        let (pass_ptr, _p) = option_to_cstring(pass);
        unsafe {
            sys::zsys_client_set_proxy(self.ptr, host_cs.as_ptr(), port, user_ptr, pass_ptr)
        };
    }

    pub fn sleep_threshold(&self) -> i32 {
        unsafe { (*self.ptr).sleep_threshold }
    }

    pub fn set_sleep_threshold(&mut self, v: i32) {
        unsafe { (*self.ptr).sleep_threshold = v }
    }

    pub fn max_concurrent(&self) -> i32 {
        unsafe { (*self.ptr).max_concurrent }
    }

    pub fn set_max_concurrent(&mut self, v: i32) {
        unsafe { (*self.ptr).max_concurrent = v }
    }

    // ── validation / serialisation ────────────────────────────────────────

    pub fn validate(&self) -> Result<(), String> {
        let mut buf = vec![0u8; 256];
        let rc = unsafe {
            sys::zsys_client_config_validate(
                self.ptr,
                buf.as_mut_ptr() as *mut c_char,
                buf.len(),
            )
        };
        if rc != 0 {
            let msg = CStr::from_bytes_until_nul(&buf)
                .map(|s| s.to_string_lossy().into_owned())
                .unwrap_or_else(|_| "validation failed".to_owned());
            Err(msg)
        } else {
            Ok(())
        }
    }

    pub fn to_json(&self) -> Result<String, &'static str> {
        let raw = unsafe { sys::zsys_client_config_to_json(self.ptr) };
        if raw.is_null() {
            return Err("zsys_client_config_to_json() failed");
        }
        let s = unsafe { CStr::from_ptr(raw).to_string_lossy().into_owned() };
        unsafe { sys::zsys_free(raw as *mut _) };
        Ok(s)
    }

    pub fn from_json(json: &str) -> Result<Self, &'static str> {
        let mut obj = Self::new()?;
        let cs = CString::new(json).map_err(|_| "null byte in json")?;
        let rc = unsafe { sys::zsys_client_config_from_json(obj.ptr, cs.as_ptr()) };
        if rc != 0 {
            Err("zsys_client_config_from_json() parse error")
        } else {
            Ok(obj)
        }
    }
}

impl Drop for ClientConfig {
    fn drop(&mut self) {
        unsafe { sys::zsys_client_config_free(self.ptr) }
    }
}

impl std::fmt::Debug for ClientConfig {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("ClientConfig")
            .field("api_id", &self.api_id())
            .field("session_name", &self.session_name())
            .field("mode", &self.mode())
            .finish()
    }
}
