"""Pure ILogger protocol for the ZSYS ecosystem.

Defines the structural contract that all loggers must satisfy.
No implementation lives here — only the interface.
"""
# RU: Чистый протокол ILogger — только контракт, никакой реализации.

from typing import runtime_checkable, Protocol


@runtime_checkable
class ILogger(Protocol):
    """Structural protocol for all ZSYS loggers."""

    def debug(self, message: str, *args, **kwargs) -> None: ...
    def info(self, message: str, *args, **kwargs) -> None: ...
    def warning(self, message: str, *args, **kwargs) -> None: ...
    def warn(self, message: str, *args, **kwargs) -> None: ...
    def error(self, message: str, *args, **kwargs) -> None: ...
    def critical(self, message: str, *args, **kwargs) -> None: ...
    def fatal(self, message: str, *args, **kwargs) -> None: ...
    def exception(self, message: str, *args, **kwargs) -> None: ...
    def log(self, level, message: str, *args, **kwargs) -> None: ...
    def set_level(self, level) -> None: ...
    def get_level(self) -> int: ...
    def is_enabled_for(self, level) -> bool: ...
    def add_handler(self, handler) -> None: ...
    def remove_handler(self, handler) -> None: ...
    def clear_handlers(self) -> None: ...
    def get_handlers(self) -> list: ...
    def enable(self) -> None: ...
    def disable(self) -> None: ...
    def is_disabled(self) -> bool: ...
    def get_child(self, suffix: str) -> "ILogger": ...
    def bind(self, **kwargs) -> "ILogger": ...


# Alias for readability
LoggerProtocol = ILogger

__all__ = ["ILogger", "LoggerProtocol"]
